[package]
name = "dodona"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
serde_with = "3.11"

[dependencies.serde]
version = "1.0"
default-features = false
features = ["derive"]

[dev-dependencies]
serde_json = "1.0"
